const allMagazin=[
{name: 'Market', reduction: 'ООО КОД'},
{name: 'Your Store', reduction: 'ООО ЛДВ'},
{name: 'Phone Talk', reduction: 'ООО БРР'},
{name: 'СмартБУМ', reduction: 'ООО ГАИ'},
{name: 'На связи!', reduction: 'ООО БРН'},
{name: 'Секретный код!', reduction: 'ООО ККЮ'},
{name: 'MyDevice', reduction: 'ООО УАО'},
{name: 'Telefonica space', reduction: 'КрДВ'},
{name: 'Mobile Paradise', reduction: 'АЭБ'},
{name: 'Cyber smart', reduction: 'ООО ПАА'},
{name: 'Бабушкин смартфон', reduction: 'ООО ОСВ'},
{name: 'Умный гаджет!', reduction: 'ООО БИК'},
{name: 'Твой выбор!', reduction: 'ООО КДВ'},
{name: 'Spice Digital', reduction: 'ГАИ'},
{name: 'Ultra mobile', reduction: 'ФЮА'},
{name: 'Smart Point', reduction: 'ПАА'},
{name: 'Screenshot', reduction: 'МРА'},
{name: 'ClarityWave ', reduction: 'ООО ФЮА'},
{name: 'iTech', reduction: 'ОСВ'},
{name: 'Телефономания', reduction: 'ООО СРД'},
{name: 'Crazy iPhone', reduction: 'АШБ'},
{name: 'iPhone company', reduction: 'КОД'},
{name: 'Mobile shop', reduction: 'ВСМ'},
{name: 'Mobile Planet', reduction: 'Ф'},
{name: 'iPhone Express', reduction: 'ЭД'},
{name: 'Mobile.store ', reduction: 'П'},
{name: 'Mobile premium', reduction: 'ДАВ'},
{name: 'Надежные смартфоны', reduction: 'ВАС'},
{name: 'Smartmarket', reduction: 'ЭД'},
{name: 'Best smartphone', reduction: 'Л'},
{name: 'Новые решения', reduction: 'М'},
{name: 'Мобильный мир', reduction: 'Р'},
{name: 'Expert Mobile', reduction: 'СВ'},
{name: 'Mobile Boom', reduction: 'ЭД'},
{name: 'MobilePro Solutions', reduction: 'БИК'},
{name: 'Dual smash', reduction: 'ООО МРА'},
{name: 'Secret Bridge', reduction: 'МИА'},
{name: 'iPhone mission', reduction: 'ООО САКВ'},
{name: 'Future', reduction: 'ООО МИА'},
{name: 'DevicePoint', reduction: 'ГИН'},
{name: 'Mobile Airtel', reduction: 'ООО ЯАД'},
{name: 'Mobile market', reduction: 'ГДЕ'},
{name: 'iPhone Place', reduction: 'ПАС'},
{name: 'Device Authority', reduction: 'РАС'},
{name: 'Mobile Leones', reduction: 'ФИИ'},
{name: 'Citywide iPhones', reduction: 'СРА'},
{name: 'Gadget Hub', reduction: 'ЭД'},
{name: 'Smart on Track', reduction: 'ПИА'}


]