const allMagazin=[
    "Market",
    "Your Store",
    "Phone Talk",
    "СмартБУМ",
    "На связи!",
    "Секретный код!",
    "MyDevice",
    "Telefonica space",
    "Mobile Paradise",
    "Cyber smart",
    "Бабушкин смартфон",
    "Умный гаджет!",
    "Твой выбор!",
    "Spice Digital",
    "Ultra mobile",
    "Smart Point",
    "Screenshot",
    "ClarityWave ",
    "iTech",
    "Телефономания",
    "Crazy iPhone",
    "iPhone company",
    "Mobile shop",
    "Mobile Planet",
    "iPhone Express",
    "Mobile.store ",
    "Mobile premium",
    "Надежные смартфоны",
    "Smartmarket",
    "Best smartphone",
    "Новые решения",
    "Мобильный мир",
    "Expert Mobile",
    "Mobile Boom",
    "MobilePro Solutions",
    "Dual smash",
    "Secret Bridge",
    "iPhone mission",
    "Future",
    "DevicePoint",
    "Mobile Airtel",
    "Mobile market",
    "iPhone Place",
    "Device Authority",
    "Mobile Leones",
    "Citywide iPhones",
    "Gadget Hub",
    "Smart on Track"
]